### ISSUE TITLE
filter.py: ImportError: cannot import name 'app_template_dirs'

### ISSUE THREAD

**Issue by karolyi** [bpeschier/django-compressor-requirejs#6]
Hey,

I'm using Django 1.8.3 with Python 3.4.3, and I have the following error when trying to use your module:

``` python
>>> import requirejs
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/.../venv/lib/python3.4/site-packages/requirejs/__init__.py", line 1, in <module>
    from .filter import RequireJSCompiler
  File "/.../venv/lib/python3.4/site-packages/requirejs/filter.py", line 8, in <module>
    from django.template.loaders.app_directories import app_template_dirs
ImportError: cannot import name 'app_template_dirs'
```

It seems that `app_template_dirs` is indeed not there:

``` python
>>> from django.template.loaders.app_directories import app_template_dirs
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name 'app_template_dirs'
```

`django.template.loaders.app_directories` has a `get_app_template_dirs` function.

Could you please fix this?

**Comment by bpeschier** [comment]
Hi,

it is already fixed in the development version, but I have not gotten around to release it since the library currently makes a couple of wrong assumptions about module paths and ids which we discovered while running it ourselves.

Thanks for the report!
