### ISSUE TITLE
Push 0.4 to PyPi

### ISSUE THREAD

**Issue by Tyrdall** [bpeschier/django-compressor-requirejs#8]
Currently only 0.3 is available. The settings since have changed so it would be great to have the current version pushed to PyPi.

**Comment by bpeschier** [comment]
Hi,

I can look into it somewhere in the coming week.

Meanwhile, I am not currently able to maintain the project much further than that, so if anybody wants to pick up development, let me know.

**Comment by Tyrdall** [comment]
Thanks for your response!
Unfortunately I recently switched to django-require :( Since there are already some forks, there might be someone who wants to continue the development.

**Comment by bpeschier** [comment]
Ah, in that case I will probably pull it since the project contains some incompatibilities with the module/path concepts in RequireJS which make it hard to use outside of relatively simple projects.

Thanks for the effort!
